import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import localFont from "next/font/local";
import Script from "next/script";

const wfFont = localFont({
  src: [
    {
      path: "../../public/assets/fonts/wf-visual-sans/WFVisualSansVF.ttf",
      weight: "500",
    },
  ],
  variable: "--wfFont",
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />

        {/* Critical CSS inline for above-the-fold content */}
        <style
          dangerouslySetInnerHTML={{
            __html: `
            .header { height: 80px; position: relative; }
            .logo-img { width: 150px; height: 50px; }
            .hero-banner { min-height: 100vh; }
            body { margin: 0; font-family: var(--font-poppins), sans-serif; }
            * { box-sizing: border-box; }
          `,
          }}
        />

        {/* Non-blocking CSS loading */}
        <link
          rel="preload"
          href="/assets/css/owl.carousel.min.css"
          as="style"
        />
        <link
          rel="stylesheet"
          href="/assets/css/owl.carousel.min.css"
          media="print"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
            document.addEventListener('DOMContentLoaded', function() {
              const link = document.querySelector('link[href="/assets/css/owl.carousel.min.css"][media="print"]');
              if (link) {
                link.media = 'all';
              }
            });
          `,
          }}
        />
        <noscript>
          <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
        </noscript>

        {/* DNS prefetch for external resources */}
        <link rel="dns-prefetch" href="//cdnjs.cloudflare.com" />
        <link rel="dns-prefetch" href="//fonts.googleapis.com" />
        <link rel="dns-prefetch" href="//fonts.gstatic.com" />

        {/* Preconnect to important origins */}
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${wfFont.variable} ${poppins.variable}`}>
        <div
          id="initial-loader"
          style={{
            height: "100vh",
            background: "#0b1b3a",
          }}
        ></div>
        {children}
        <Script src="/assets/js/jquery-3.7.1.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/owl.carousel.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
