import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import localFont from "next/font/local";

const wfFont = localFont({
  src: [
    {
      path: "../../public/assets/fonts/wf-visual-sans/WFVisualSansVF.ttf",
      weight: "500",
    },
  ],  
  variable: "--wfFont",
});  

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="/assets/css/style.css" /> */}
        <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"          
        />

        <script src="/assets/js/jquery-3.7.1.min.js"></script>
        <script src="/assets/js/owl.carousel.min.js"></script>
      </head>
      <body className={`${wfFont.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
